### ISSUE TITLE
Chiamata metodo da diag. di attività

### ISSUE THREAD

**Issue by oigroig** [hivex-unipd/swedesigner#58]
Dal diagramma di attività, se voglio chiamare il metodo di un oggetto (tipo il metodo `setSize(3)` dell'oggetto `pippo`, così: `pippo.setSize(3)`) devo ricorrere al seguente hack:
* inserisco una nuova variabile;
* nel campo Nome, inserisco "pippo";
* nel campo Operazione, devo inserire "." (ma io vorrei inserire "setSize");
* nel campo Valore, mi tocca inserire "setSize(3)" (ma intuitivamente vorrei inserire soltanto "3").

**Comment by xBerga95** [comment]
That's a feature!
